# 只针对Node.js项目进行CI/CD(/app 目录之下)
name: Node CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: 'Node.js version to use'
        default: '22'
        type: string

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22]
      fail-fast: true
    defaults:
      run:
        shell: bash
        working-directory: app
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: app/package-lock.json
      - run: npm ci
      - run: npm run lint
      - run: npm run test:ci
      - run: npm run build:ci

      - name: upload test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: node-test-report-${{ matrix.node-version }}
          path: app/reports/junit.xml
          retention-days: 5

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   codecheck:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#   lint:
#     runs-on: ubuntu-latest
#     steps:
#       - run: npm run lint
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - run: npm run test
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - run: npm run build

#       - name: Run a one-line script
#         run: echo Hello, world!


